### ISSUE TITLE
(possible) violation bbc.net.uk

### ISSUE THREAD

**Issue by hannesm** [dns-violations/dns-violations#50]
first of all, thank you so much for starting this project!

I'm not entirely sure here, but there may be an issue here:

```
# dig SOA bbc.net.uk @ns0.rbsov.bbc.co.uk +noedns
bbc.net.uk.             3600    IN      SOA     212.58.225.6. bofh.bbc.co.uk. 1502097794 86400 86400 86400 300
```

there are two things here:
- I've to use `+noedns`, otherwise getting a `FormErr`
- the `mname` field of the SOA is an IPv4 address encoded as label, rather than a hostname.  it is not entirely clear to me from RFC1035 whether it must be a hostname or not (at least, this is so far the only zone where I saw an IP rather than a hostname)

**Comment by hannesm** [comment]
anyone has comments for this issue?

**Comment by andrewtj** [comment]
I'm not involved with this project but for my random $0.02, `FORMERR` is fine as a signal that the server doesn't support EDNS ([RFC 6891 - Section 7](https://tools.ietf.org/html/rfc6891#section-7)). 

What's not so okay is that dig reports extra bytes in the response when EDNS is enabled. The number of bytes varies depending on the number of extended options in the query which suggests the server is echoing back part of the query message verbatim. I haven't verified this with another other tool though.

The SOA's MNAME doesn't matter too much. It's a valid domain name so its content is only a problem for them.

**Comment by oerdnj** [comment]
@hannesm Sorry for the late reply. The real life too precedence.

I think @andrewtj is right, this is not a protocol violation as the resolver can work with FORMERR, but only an unfortunate decision at the `bbc.co.uk` side.
