### ISSUE TITLE
dnsmasq <=2.79 omits EDNS0 OPT records on some responses

### ISSUE THREAD

**Issue by srd424** [dns-violations/dns-violations#62]
## Description

dnsmasq 2.79 and below omits EDNS0 OPT records when returning an empty answer for a domain it is authoritative for, even if they were present on the query. The violates RFC 6891.

systemd-resolved 237 seems to get confused by this in certain circumstances; when using the stub resolver and requesting an address for which there are no AAAA records, there can sometimes be a five second hang in resolution. systemd 239 doesn't exhibit this behaviour: 

https://github.com/systemd/systemd/issues/9785

## Evidence

Simple-ish test case:
```
IFACE=dummy0
SUBNET=10.0.0

ip link add $IFACE type dummy
ifconfig $IFACE ${SUBNET}.1/24
dnsmasq -h -R -d -C /dev/null -2 $IFACE -z -i $IFACE -I lo --host-record=test.test,${SUBNET}.1 &

dig -t a test.test @10.0.0.1 | grep EDNS
# should return "; EDNS ..."
dig -t aaaa test.test @10.0.0.1 | grep EDNS
# again, should return "; EDNS ..." but doesn't
```
## Proposed Fix / Vendor Response

This is fixed by upstream commit http://thekelleys.org.uk/gitweb/?p=dnsmasq.git;a=commit;h=1682d15a744880b0398af75eadf68fe66128af78

## Metadata

Submitter: Steve Dodd
Submit-Date: 2018-08-05
Report-Date: 2018-08-03 Simon Kelley <simon@thekelleys.org.uk>
Fixed-Date: 2018-08-03
Tags: edns0,edns
<meta-data>: <value>

**Comment by pspacek** [comment]
Please transform this into pull request, I will be happy to merge this.
