### ISSUE TITLE
Non-singleton CNAME RRset from Gandi

### ISSUE THREAD

**Issue by edmonds** [dns-violations/dns-violations#63]
If someone wants to convert this to a DVE…

```
; <<>> DiG 9.11.4-4-Debian <<>> +norec @a.dns.gandi.net lib.protobuf-c.io.
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 1187
;; flags: qr aa; QUERY: 1, ANSWER: 2, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;lib.protobuf-c.io.		IN	A

;; ANSWER SECTION:
lib.protobuf-c.io.	10800	IN	CNAME	protobuf-c.github.io.
lib.protobuf-c.io.	10800	IN	CNAME	protobuf-c.github.io.

;; Query time: 107 msec
;; SERVER: 173.246.98.1#53(173.246.98.1)
;; WHEN: Fri Aug 17 15:35:13 EDT 2018
;; MSG SIZE  rcvd: 92
```

**Comment by baloo** [comment]
(speaking for gandi)

Please note this issue has been resolved this morning around 9am CEST.
We do not have a full analysis of the issue yet.

As a personal note, it would have been appreciated to have vendor contacted either via support or Twitter along with the issue being opened here. We could have missed it if we were not watching this repository.

Thanks for the report!

**Comment by oerdnj** [comment]
> As a personal note, it would have been appreciated to have vendor contacted either via support or Twitter along with the issue being opened here.

That would be a case before generating DVE.  No worries.
