### ISSUE TITLE
DVE-2017-0009 is resolved

### ISSUE THREAD

**Issue by vdukhovni** [dns-violations/dns-violations#68]
If this project is no longer active and the data getting increasing stale, perhaps the DVEs should be archived and closed.  In any case DVE-2017-0009 is resolved.

**Comment by pspacek** [comment]
Fixed by merge.

**Comment by pspacek** [comment]
Let me clarify that this is a community project, so it is as alive as interest of its contributors. There is no automation to check if already reported DVEs are still valid or not.
